### ISSUE TITLE
how to run glogic?

### ISSUE THREAD

**Issue by petaflot** [astraldev/GLogic#1]
installation instructions are good, python module import caused no problem... what next? how to get the UI?

**Comment by petaflot** [comment]
```
$ python run.py
```

quite straightforward in fact, but it wouldn't hurt stating it in the doc.

**Comment by astraldev** [comment]
Do you have any new issues? Cause I think it's icon should appear on your desktop....

**Comment by petaflot** [comment]
I have _zero_ icon on my desktop (not from any app, not any file... I like to keep my desktop clean)

issues Iface are:
-  the UI is horrible to use : too many clicks and keyboard strokes for repetitive stuff.
- no propagation delay settable on lines, other timing limitations

on the other hand there's enough done to make it usable, so I might fork it and maybe you like some of the changes I add.

**Comment by astraldev** [comment]
Please which distribution are you using ? And your system specs..... If possible, send a video of your issues and I'll see what I can do.... Sorry for the discomfort. Also, the release is outdated you'll have to run the project from the main repo
